branch: "main"
preset: "conventionalcommits"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - successCmd: |
        echo ${nextRelease.version} > VERSION
        echo ${nextRelease.gitTag} > GIT_TAG